print("Challenge 11")
birthplace = input ("Where were you born?")
age = input ("What is your age?")
fav_icecream = input ("What is your favorite icecream flavor?")
fav_movie = input ("What is your favorite movie?")
fav_colour = input ("What is your favorite colour?")
print ("I have learned from you that:")
print ("You were born in" + birthplace)
print ("You are" + age + " years old and you love" + fav_icecream + " icecream.")
print( "I think maybe one day we could watch" + fav_movie + " together")

